log-level: FINE
webhook:
  enabled: false
  port: env(PORT:8443)
  externalUrl: https://123.45.67.890:$port
  internalUrl: http://0.0.0.0:$port
  # keystorePath: cert/keystore.jks
  # keystorePassword: env(KEYSTORE_PASSWORD)
modules:
  - com.annimon.testbot.TestBot