

FROM adoptopenjdk/openjdk11:ubi
ARG NODE_ROOT
RUN echo NODE_ROOT_Project $NODE_ROOT
RUN cd
RUN dir $NODE_ROOT
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java", "-Dbot.username=${BOT_NAME}", "-Dbot.token=${BOT_TOKEN}", "-jar", "/app.jar"]